version: '3.9'

secrets:
  db_user:
    file: ./secrets/db_user.txt
  db_pwd:
    file: ./secrets/db_pwd.txt
  db_root_pwd:
    file: ./secrets/db_root_pwd.txt


services:
  bot:
    build: ./app
    
    secrets:
      - db_user
      - db_pwd
    
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mysql:8.0.28
    restart: always

    secrets:
      - db_user
      - db_pwd
      - db_root_pwd
    environment:
      - MYSQL_DATABASE=robocorg
      - MYSQL_USER_FILE=/run/secrets/db_user
      - MYSQL_PASSWORD_FILE=/run/secrets/db_pwd
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_pwd
    
    ports:
      - 3306:3306
    
    volumes:
      - robocorg-db:/data/db
    
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  robocorg-db:

