version: '3.9'

services:
  bot:
    build: ./app
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
        
  db:
    image: mysql:8.0.28
    restart: always

    environment:
      MYSQL_DATABASE: robocorg
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
    
    ports:
      - 3306:3306
    
    volumes:
      - robocorg-db:/data/db
    
    env_file:
      - .env

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  robocorg-db: